### ISSUE TITLE
Lxplus Ninja 

### ISSUE THREAD

**Issue by petitcactusorange** [lhcb/scheduling-event-model#22]
@GerhardRaven I am giving a try to running your code. 
First issue : Ninja is not installed by default on lxplus it seems

[yamhis@lxplus0067 TransformAlgorithm_playground]$ source setup-lhcb-build.sh 
/usr/bin/which: no ninja in (/afs/cern.ch/group/z5/bin:/afs/cern.ch/user/y/yamhis/scripts:/usr/kerberos/sbin:/afs/cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v8r4p2/InstallArea/scripts:/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/lhcb/software/releases/COMPAT/COMPAT_v1r19/CompatSys/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/contrib/CMT/v1r20p20090520/Linux-x86_64:/afs/cern.ch/lhcb/bin:/afs/cern.ch/sw/lcg/contrib/CMake/2.8.9/Linux-i386/bin:/usr/sue/bin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin)
Ninja is not installed. Will Install Ninja ..

**Comment by petitcactusorange** [comment]
@bencouturier it's available with : 
 export PATH=${PATH}:/afs/cern.ch/sw/lcg/contrib/ninja/1.4.0/x86_64-slc6/

**Comment by GerhardRaven** [comment]
The fact that Ninja isn't installed isn't a problem. You'll see that it downloads & compiles it, and then uses it ;-) (note: 'Will install Ninja..." comment.
Haven't bothered to suppress the output from `which`. Should be easy as adding >& /dev/null...

**Comment by petitcactusorange** [comment]
ahhhhhhhh fair enough :-)

**Comment by GerhardRaven** [comment]
I've just merged a pull request from myself which doesn't spam your output when it doesn't find something optional...
