### ISSUE TITLE
Contribution from Florian

### ISSUE THREAD

**Issue by petitcactusorange** [lhcb/scheduling-event-model#7]
Find attached  the work that Florian(*) has done during the summer  to “accelerate” tracking code.  
We discussed with Ben and Lionel the possibility of having him involved in the workshop.  My idea was to ask him to give us feed back  (a sort of review) on what were the 
bottle necks and what seem to slow down any code acceleration in the current LHCb software. Since he is didn’t work on the current Event Model he might have an unbiased view. 

What do you think ? 
[Florian.pdf](https://github.com/lhcb/scheduling-event-model/files/6635/Florian.pdf)
(*) Florian was a technical student and he will start his PhD tomorrow supervised by Ben at CERN and Lionel Lacassagne in Paris.

**Comment by lemaitre** [comment]
Hi everybody,

After a discussion with Yasmine and Ben, it was suggested that I take the Outer Tracker Reconstruction algorithm (from May) and I change the memory layout (AoS -> SoA) in order to show what gain we can hope, and why (according my previous study).

Florian

**Comment by betatim** [comment]
Sounds good. Can you commit to the LHCb svn repository to keep track of your work? Otherwise you could use this repository if you wish.

**Comment by petitcactusorange** [comment]
@lemaitre can I close this issue?

**Comment by lemaitre** [comment]
I have nothing to add.
Or maybe the link of my repository:
/afs/cern.ch/user/f/flemaitr/public/DevelopSeeding.git

However, I have now some difficulties, so there is no big changes for a while.

**Comment by petitcactusorange** [comment]
Thanks !

**Comment by lemaitre** [comment]
Just for you to know:
My repository is know on gitlab too:
https://gitlab.cern.ch/flemaitr/SciFi-Seeding
