### ISSUE TITLE
Upgrade tracking 

### ISSUE THREAD

**Issue by petitcactusorange** [lhcb/scheduling-event-model#9]
The current performances of the upgrade tracking will be probably used as input for discussion in various sessions. 
I wonder if we want to have a dedicated contribution ? Or simply gather the information (slides?) and s have them available.  What do you think ?

**Comment by betatim** [comment]
I don't think having a dedicated contribution in this session is useful. You need an order of magnitude estimate but beyond that I don't think that the concrete number for the current algorithm, with the current simulation, and all the approximations they contain should have that much influence on our decisions.

**Comment by petitcactusorange** [comment]
Ok, great. I was thinking the same. We just have to figure out who to ask to get this information.

**Comment by petitcactusorange** [comment]
Checked with @betatim, will ask Sevda to provide numbers.
